### ISSUE TITLE
Expert directory backend

### ISSUE THREAD

**Issue by w-dib** [Callmi-org/callmi#50]
Start with figma file [here](https://www.figma.com/file/yTlrDFJF4qnLyckQq2tsRi/Callmi---Client?type=design&node-id=1279-8241&mode=design&t=79rsdvblXq07Jg6c-0).

### ONLY EXPERTS WITH THE FEATURED TAG CAN SHOW ON THIS PAGE'S DEFAULT SECTIONS. 

Below is what the featured tag looks like:

![image](https://github.com/Callmi-org/callmi/assets/112762655/a1c8fb3e-6427-476d-9edd-890d90117248)

Note: @Aadil-Shabir @mo-shawa all existing experts default verified to `true` on Prisma on prod. All new joiners default verified to `false`.

---

Each one of the below sections should lead to their own section in the same page:

![image](https://github.com/Callmi-org/callmi/assets/112762655/8b6bd583-bbab-4c32-b778-e85165a3d45d)

Within these sections, you should extract info from the back end for each section's cards based on the expertise.

**Design your Ideal Career**: Bootstrapping, People & Hiring, Coaching, Product & Engineering

**Close Your Funding Round**: Financial Planning, Fundraising, Strategy & Operations

**Find Product Market Fit**: B2B Sales, B2C Sales, Branding, Growth Marketing, Manufacturing, Product Marketing, Product & Engineering, Public Relations, SEM & SEO, Social Media, Strategy & Operations

It's OK that some of the above have repeated expertise. There is an overlap.

---

Each card (e.g.: shown below) should take the following from the database:

![image](https://github.com/Callmi-org/callmi/assets/112762655/37af6700-0570-47e3-9f49-b196d87183c5)

- Profile picture
- Position
- Company name (if not null, if null then blank)
- First 75 characters then truncate
- Up to 2 expertise and "+1"
- Up to 2 industries
- Price/hour
- 5 stars hard coded for now

---

### Searching

![image](https://github.com/Callmi-org/callmi/assets/112762655/3031574f-a1cf-40b1-a68d-6231d636866b)

Search defaults to a search by firstname or last name of ALL experts in Prisma, whether featured or not

### Filtering and sorting

![image](https://github.com/Callmi-org/callmi/assets/112762655/58f82150-98f5-4f20-afb9-8a8b43646c1d)

If filtering and sorting is difficult, let's go live with the basics (i.e.: just the expertise pills)

**Comment by mo-shawa** [comment]
## My thoughts and birds eye plan for this feature

### Schema update

We're going to have to do a live schema update to add the `featured` boolean property on the `User` model. Given that our dev data does not closely resemble live data and that this is inherently risky, I'm going to set up another deployment ASAP, likely under <staging.callmi.co>. The schema update process will look like this:

1. Create staging branch on Neon and Vercel deployment
2. Build and test locally with changed schema
3. Test schema deployment on `dev`
4. Test schema on a copy of live data on `staging`
5. Deploy changes onto `main`

This is my task - in the meantime @Aadil-Shabir you can continue working on the front end, and merge in the update from my side once it is pushed up.

### Search and sort features

There are more and less "correct" ways to implement this feature. Given prioritization of fast implementation, here's pseudocode suggestion for the backend:

I believe `GET` functions in app router results are cached and not automatically revalidated by default. It will also not appear to be a problem on local dev server since it behaves quite differently from production build. @Aadil-Shabir Please look into if this affects our use case here and possibly opting out of this behaviour.

- Search by name could simply be a `prisma.findMany` where `name: {contains: "searched name"}`
- Search by expertise or industry maybe more tricky, but something like this should work: 
```ts
import { NextRequest } from 'next/server'
import prisma from '@/utils/prisma'
import { Expertise } from '@prisma/client'
export async function GET(req: NextRequest) {
  
  const expertises: Expertise[] = ['Fundraising', 'Bootstrapping']

  const result = await prisma.user.findMany({
    where: {
      expertise: {
        hasSome: expertises,
      },
    },
  })


  return Response.json(result)
}
```
 
(make sure to convert between the enums and the string version - there are helper functions in `utils/prisma`)

Of course, you will have to write logic to generate the query depending on the options chosen by the user but I will leave that to you.

### Estimate

I would say this simpler implementation would take about a day of focused work, possibly a another to iron out issues and glue all the pieces together. My schema update and staging deployment should be done in the next 4 hours, but may take more or less depending on DNS issues for example. 





@Aadil-Shabir This should be helpful: https://www.prisma.io/docs/orm/prisma-client/queries/filtering-and-sorting

**Comment by w-dib** [comment]
@Aadil-Shabir  Now that we have the featured users boolean, shown below:

![image](https://github.com/Callmi-org/callmi/assets/112762655/b6ae4edc-ea51-4e84-960d-971fdfc2a039)

let's make sure we implement it like so: 

![image](https://github.com/Callmi-org/callmi/assets/112762655/69da06b3-e226-4d10-a2d2-d2dcb1f7b301)

Below are the prisma usernames per section, in order:

### CAREER
- telmomartins
- lauradryden
- zeinannab
- zeinnemri
- basharfaouri
- hatemgoucha
- khaledghorab
- islamismail

### FUNDRAISING

- jadhalaoui
- youssefsalem
- catherinaballout
- ahmedkhairy
- hamedmasri
- siddiqfarid1
- tameral-salah
- jonedwardsantillan
- nafezdakkak
- anserabdullatheef
- jamesevans
- hazem
- mohammadalzaben
- justinjoseph
- mohammedalrasbi
- faisalalbitar
- naseervianet.capita
- waliddibl
- fouadjeryes1
- ashugupta
- mahmoudgao
- tinayildirim

### PRODUCT MARKET FIT

- richardfitzgerald
- shereenabdulla
- avinashbabur
- hassanainanver
- mahmoudshawa1
- constantinkodsi
- ahmedhany
- islamismail
- eliastsikhlakis
- danashaheen
- wajdbadawi
- shereenabdulla
- ashugupta
- martino'leary1
- dommonhardt
- ashrafal-khalili
- adeelfarooq
- jadhalaoui
